version: '3'
services:
  api:
    build: .
    ports:
      - "5000:3000"
    volumes:
      - .:/app
    # command: npm run dev
    platform: linux/amd64
    depends_on:
      - db
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_HOST=db
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydb
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "9999:8080"
    environment:
      - SWAGGER_JSON=/mnt/swagger.yml
    volumes:
      - ./docs:/mnt
