version: '3'
services:
  api:
    build: .
    ports:
      - "5000:3000"
    volumes:
      - .:/app
    command: npm run dev
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "9999:8080"
    environment:
      - SWAGGER_JSON=/mnt/swagger.yml
    volumes:
      - ./docs:/mnt
